# plugins:
#   - jekyll-remote-theme

# # remote_theme: flancast90/millidocs-dark

# Site settings
title: The New (New) Blog
email:
description: "Atonement for a Temporarily Embarrassed Scientist"
baseurl: "" # Replace <repository> with your repo name
url: "https://seamusbarnes.github.io"

twitter_username: Seaumus_Barnes
github_username: seamusbarnes

# Build settings
markdown: kramdown
permalink: pretty

incremental: false
watch: true

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

navigation:
  - title: "Home"
    url: /
  - title: "Welcome"
    url: /welcome/
  - title: "Tags"
    url: /tags/
