# Site settings
title: The New Blog
email:
description: "Atonement for a temporarily embarrassed scientist"
baseurl: ""
url: "http://seamusbarnes.github.io"
twitter_username: Seaumus_Barnes
github_username: seamusbarnes

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
